CREATE TABLE "expert" (
	"id"	INTEGER,
	"salutation"	INTEGER NOT NULL,
	"firstName"	TEXT NOT NULL,
	"midName"	TEXT NOT NULL,
	"lastName"	TEXT NOT NULL,
	"gender"	INTEGER NOT NULL,
	"job"	TEXT NOT NULL,
	"experience"	TEXT NOT NULL,
	"projects"	TEXT NOT NULL,
	"publications"	TEXT NOT NULL,
	"businessUnit"	TEXT NOT NULL,
	"organisation"	TEXT NOT NULL,
	"address"	TEXT NOT NULL,
	"country"	INTEGER NOT NULL,
	"email"	TEXT NOT NULL,
	"mobile"	TEXT NOT NULL,
	"fax"	TEXT NOT NULL,
	"profileUrl"	TEXT NOT NULL,
	"image"	TEXT NOT NULL,
	"onlineStatus"	INTEGER NOT NULL,
	"submissionTime"	INTEGER NOT NULL,
	"lastUpdated"	INTEGER NOT NULL,
	"expiresOn"	INTEGER NOT NULL,
	"metaTitle"	TEXT NOT NULL,
	"metaDescription"	TEXT NOT NULL,
	"metaSeo"	TEXT NOT NULL,
	PRIMARY KEY("id")
);